const express = require("express");
const session = require("express-session");
const pgSession = require("connect-pg-simple")(session);
const { Pool } = require("pg");
const helmet = require("helmet");
const multer = require("multer");
const path = require("path");
const fs = require("fs");
const crypto = require("crypto");

const app = express();
app.set("trust proxy", 1);
const PORT = process.env.PORT || 3000;
const ROOT = __dirname;

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error(
    "SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY is missing."
  );
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

const SUPABASE_URL =
  process.env.SUPABASE_URL;

const SUPABASE_SERVICE_ROLE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY;

const query = (text, params = []) =>
  pool.query(text, params);

const hash = s =>
  crypto.createHash("sha256").update(String(s)).digest("hex");

function slugify(s) {
  return String(s)
    .trim()
    .toLowerCase()
    .replace(/[^\u0E00-\u0E7Fa-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") ||
    crypto.randomBytes(5).toString("hex");
}

function articleRow(a) {
  return {
    ...a,
    featured: !!a.featured
  };
}

function requireAuth(req, res, next) {
  if (req.session.user) return next();
  res.status(401).json({
    error: "Please login first."
  });
}

/* ==========================================
   APP
========================================== */

app.use(
  helmet({
    contentSecurityPolicy: false
  })
);

app.use(express.json({ limit: "2mb" }));
app.use(express.urlencoded({ extended: true }));

app.use(
  session({
    store: new pgSession({
      pool,
      tableName: "user_sessions",
      createTableIfMissing: true
    }),
    secret:
      process.env.SESSION_SECRET ||
      "CHANGE_THIS_SESSION_SECRET",
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      maxAge: 1000 * 60 * 60 * 8
    }
  })
);

app.use(express.static(path.join(ROOT, "public")));

/* ==========================================
   STARTUP
========================================== */

async function setup() {
  await query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS categories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT UNIQUE NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS articles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      excerpt TEXT DEFAULT '',
      content TEXT DEFAULT '',
      image TEXT DEFAULT '',
      category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
      author TEXT DEFAULT 'YouthNews',
      status TEXT DEFAULT 'published',
      featured BOOLEAN DEFAULT FALSE,
      views BIGINT DEFAULT 0,
      published_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS homepage_sections (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      section_type TEXT DEFAULT 'category',
      category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
      position INTEGER DEFAULT 0,
      columns_count INTEGER DEFAULT 2,
      enabled BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      event_date DATE,
      event_time TEXT DEFAULT '',
      location TEXT DEFAULT '',
      description TEXT DEFAULT '',
      enabled BOOLEAN DEFAULT TRUE,
      position INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS trending_topics (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label TEXT NOT NULL,
      slug TEXT NOT NULL,
      position INTEGER DEFAULT 0,
      enabled BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS navigation (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label TEXT NOT NULL,
      url TEXT NOT NULL,
      position INTEGER DEFAULT 0,
      enabled BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
  `);

  await seedCategories();
  await seedSettings();
  await seedNavigation();
  await seedAdmin();

  console.log("YouthNews database ready.");
}

/* ==========================================
   SEED CATEGORIES
========================================== */

async function seedCategories() {
  const categories = [
    ["RMUTK News", "rmutk-news"],
    ["General", "general"],
    ["Training News", "training-news"],
    ["Career", "career"],
    ["Student Voice", "student-voice"]
  ];

  for (const [name, slug] of categories) {
    await query(
      `
      INSERT INTO categories(name, slug)
      VALUES($1,$2)
      ON CONFLICT (slug) DO NOTHING
      `,
      [name, slug]
    );
  }
}

/* ==========================================
   SEED SETTINGS
========================================== */

async function seedSettings() {
  const settings = [
    ["site_name", "YOUTH NEWS"],
    [
      "tagline",
      "Stories for the next generation."
    ],
    [
      "breaking",
      "Latest updates from the campus community."
    ],
    ["facebook", "#"],
    ["instagram", "#"],
    ["contact", "news@youthnews.local"]
  ];

  for (const [key, value] of settings) {
    await query(
      `
      INSERT INTO settings(key,value)
      VALUES($1,$2)
      ON CONFLICT(key) DO NOTHING
      `,
      [key, value]
    );
  }
}

/* ==========================================
   SEED NAVIGATION
========================================== */

async function seedNavigation() {
  const items = [
    ["Home", "/", 1],
    ["RMUTK News", "/?category=rmutk-news", 2],
    ["General", "/?category=general", 3],
    ["Training News", "/?category=training-news", 4],
    ["Career", "/?category=career", 5],
    ["Student Voice", "/?category=student-voice", 6]
  ];

  for (const [label, url, position] of items) {
    await query(
      `
      INSERT INTO navigation(label,url,position)
      SELECT $1,$2,$3
      WHERE NOT EXISTS (
        SELECT 1 FROM navigation
        WHERE label=$1
      )
      `,
      [label, url, position]
    );
  }
}

/* ==========================================
   ADMIN
========================================== */

async function seedAdmin() {
  const username =
    process.env.ADMIN_USER || "admin";

  const password =
    process.env.ADMIN_PASSWORD ||
    "change-me-now";

  const existing = await query(
    `SELECT id FROM users WHERE username=$1`,
    [username]
  );

  if (existing.rowCount === 0) {
    await query(
      `
      INSERT INTO users(username,password_hash)
      VALUES($1,$2)
      `,
      [username, hash(password)]
    );

    console.log(
      `Admin created: ${username}`
    );
  }
}

/* ==========================================
   SETTINGS
========================================== */

app.get("/api/settings", async (req, res) => {
  try {
    const r = await query(
      `SELECT key,value FROM settings`
    );

    res.json(
      Object.fromEntries(
        r.rows.map(x => [x.key, x.value])
      )
    );
  } catch (e) {
    console.error(e);
    res.status(500).json({
      error: "Failed to load settings"
    });
  }
});

app.put(
  "/api/settings",
  requireAuth,
  async (req, res) => {
    try {
      for (const [key, value] of Object.entries(
        req.body
      )) {
        await query(
          `
          INSERT INTO settings(key,value)
          VALUES($1,$2)
          ON CONFLICT(key)
          DO UPDATE SET value=EXCLUDED.value
          `,
          [key, String(value)]
        );
      }

      res.json({ ok: true });
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to save settings"
      });
    }
  }
);

/* ==========================================
   CATEGORIES
========================================== */

app.get("/api/categories", async (req, res) => {
  try {
    const r = await query(
      `SELECT * FROM categories ORDER BY id`
    );

    res.json(r.rows);
  } catch (e) {
    console.error(e);
    res.status(500).json({
      error: "Failed to load categories"
    });
  }
});

app.post(
  "/api/categories",
  requireAuth,
  async (req, res) => {
    try {
      const { name, slug } = req.body;

      if (!name) {
        return res.status(400).json({
          error: "Category name is required."
        });
      }

      const finalSlug =
        slug || slugify(name);

      const r = await query(
        `
        INSERT INTO categories(name,slug)
        VALUES($1,$2)
        RETURNING *
        `,
        [name, finalSlug]
      );

      res.json(r.rows[0]);
    } catch (e) {
      console.error(e);
      res.status(400).json({
        error: "Category already exists or is invalid."
      });
    }
  }
);

app.put(
  "/api/categories/:id",
  requireAuth,
  async (req, res) => {
    try {
      const { name, slug } = req.body;

      await query(
        `
        UPDATE categories
        SET name=$1,slug=$2
        WHERE id=$3
        `,
        [
          name,
          slug || slugify(name),
          req.params.id
        ]
      );

      res.json({ ok: true });
    } catch (e) {
      console.error(e);
      res.status(400).json({
        error: "Failed to update category"
      });
    }
  }
);

app.delete(
  "/api/categories/:id",
  requireAuth,
  async (req, res) => {
    try {
      await query(
        `DELETE FROM categories WHERE id=$1`,
        [req.params.id]
      );

      res.json({ ok: true });
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to delete category"
      });
    }
  }
);

/* ==========================================
   ARTICLES
========================================== */

app.get("/api/articles", async (req, res) => {
  try {
    const {
      category,
      search,
      featured,
      limit = 30,
      page = 1
    } = req.query;

    const conditions = [
      `a.status='published'`
    ];

    const params = [];

    if (category) {
      params.push(category);
      conditions.push(
        `c.slug=$${params.length}`
      );
    }

    if (featured === "1") {
      conditions.push(`a.featured=TRUE`);
    }

    if (search) {
      params.push(`%${search}%`);
      const p = `$${params.length}`;

      conditions.push(
        `(a.title ILIKE ${p}
          OR a.excerpt ILIKE ${p}
          OR a.content ILIKE ${p})`
      );
    }

    const lim = Math.min(
      Number(limit) || 30,
      100
    );

    const off =
      (Math.max(Number(page) || 1, 1) - 1) *
      lim;

    params.push(lim);
    const limitParam = `$${params.length}`;

    params.push(off);
    const offsetParam = `$${params.length}`;

    const r = await query(
      `
      SELECT
        a.*,
        c.name AS category_name,
        c.slug AS category_slug
      FROM articles a
      LEFT JOIN categories c
        ON c.id=a.category_id
      WHERE ${conditions.join(" AND ")}
      ORDER BY
        a.featured DESC,
        a.published_at DESC
      LIMIT ${limitParam}
      OFFSET ${offsetParam}
      `,
      params
    );

    res.json(r.rows.map(articleRow));
  } catch (e) {
    console.error(e);
    res.status(500).json({
      error: "Failed to load articles"
    });
  }
});

/* ==========================================
   SINGLE ARTICLE
========================================== */

app.get(
  "/api/articles/:slug",
  async (req, res) => {
    try {
      const r = await query(
        `
        SELECT
          a.*,
          c.name AS category_name,
          c.slug AS category_slug
        FROM articles a
        LEFT JOIN categories c
          ON c.id=a.category_id
        WHERE a.slug=$1
        AND a.status='published'
        `,
        [req.params.slug]
      );

      if (!r.rowCount) {
        return res.status(404).json({
          error: "Article not found"
        });
      }

      const article = r.rows[0];

      await query(
        `
        UPDATE articles
        SET views=views+1
        WHERE id=$1
        `,
        [article.id]
      );

      article.views =
        Number(article.views || 0) + 1;

      res.json(articleRow(article));
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to load article"
      });
    }
  }
);

/* ==========================================
   CREATE ARTICLE
========================================== */

app.post(
  "/api/articles",
  requireAuth,
  async (req, res) => {
    try {
      const {
        title,
        excerpt,
        content,
        image,
        category_id,
        author,
        status = "published",
        featured = false
      } = req.body;

      if (!title) {
        return res.status(400).json({
          error: "Title is required."
        });
      }

      const slug =
        slugify(title) +
        "-" +
        Date.now().toString().slice(-5);

      const r = await query(
        `
        INSERT INTO articles
        (
          title,
          slug,
          excerpt,
          content,
          image,
          category_id,
          author,
          status,
          featured
        )
        VALUES
        ($1,$2,$3,$4,$5,$6,$7,$8,$9)
        RETURNING *
        `,
        [
          title,
          slug,
          excerpt || "",
          content || "",
          image || "",
          category_id || null,
          author || "YouthNews",
          status,
          !!featured
        ]
      );

      res.json(articleRow(r.rows[0]));
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to create article"
      });
    }
  }
);

/* ==========================================
   UPDATE ARTICLE
========================================== */

app.put(
  "/api/articles/:id",
  requireAuth,
  async (req, res) => {
    try {
      const {
        title,
        excerpt,
        content,
        image,
        category_id,
        author,
        status,
        featured
      } = req.body;

      await query(
        `
        UPDATE articles
        SET
          title=$1,
          excerpt=$2,
          content=$3,
          image=$4,
          category_id=$5,
          author=$6,
          status=$7,
          featured=$8,
          updated_at=NOW()
        WHERE id=$9
        `,
        [
          title,
          excerpt || "",
          content || "",
          image || "",
          category_id || null,
          author || "YouthNews",
          status || "published",
          !!featured,
          req.params.id
        ]
      );

      res.json({ ok: true });
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to update article"
      });
    }
  }
);

/* ==========================================
   DELETE ARTICLE
========================================== */

app.delete(
  "/api/articles/:id",
  requireAuth,
  async (req, res) => {
    try {
      await query(
        `DELETE FROM articles WHERE id=$1`,
        [req.params.id]
      );

      res.json({ ok: true });
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to delete article"
      });
    }
  }
);

/* ==========================================
   LOGIN
========================================== */

app.post("/api/login", async (req, res) => {
  try {
    const {
      username,
      password
    } = req.body;

    const r = await query(
      `
      SELECT *
      FROM users
      WHERE username=$1
      AND password_hash=$2
      `,
      [
        username,
        hash(password || "")
      ]
    );

    if (!r.rowCount) {
      return res.status(401).json({
        error:
          "Invalid username or password."
      });
    }

    req.session.user = {
      id: r.rows[0].id,
      username: r.rows[0].username
    };

    res.json({
      ok: true,
      username: r.rows[0].username
    });
  } catch (e) {
    console.error(e);
    res.status(500).json({
      error: "Login failed"
    });
  }
});

app.post(
  "/api/logout",
  (req, res) => {
    req.session.destroy(() => {
      res.json({ ok: true });
    });
  }
);

app.get(
  "/api/me",
  (req, res) => {
    res.json(
      req.session.user || null
    );
  }
);

/* ==========================================
   IMAGE UPLOAD - SUPABASE STORAGE
========================================== */

const storage = multer.memoryStorage();

const upload = multer({
  storage,
  limits: {
    fileSize: 8 * 1024 * 1024
  },
  fileFilter: (_, file, cb) => {
    cb(
      null,
      /^image\/(jpeg|png|webp|gif|svg\+xml)$/.test(
        file.mimetype
      )
    );
  }
});

app.post(
  "/api/upload",
  requireAuth,
  upload.single("image"),
  async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({
          error: "Please select an image."
        });
      }

      if (
        !SUPABASE_URL ||
        !SUPABASE_SERVICE_ROLE_KEY
      ) {
        return res.status(500).json({
          error:
            "Supabase Storage environment variables are missing."
        });
      }

      const filename =
        Date.now() +
        "-" +
        crypto.randomBytes(4).toString("hex") +
        path.extname(req.file.originalname).toLowerCase();

      const uploadUrl =
        `${SUPABASE_URL}/storage/v1/object/news-images/${filename}`;

      const uploadResponse = await fetch(
        uploadUrl,
        {
          method: "POST",
          headers: {
            Authorization:
              `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
            apikey:
              SUPABASE_SERVICE_ROLE_KEY,
            "Content-Type":
              req.file.mimetype,
            "Cache-Control":
              "3600"
          },
          body: req.file.buffer
        }
      );

      if (!uploadResponse.ok) {
        const errorText =
          await uploadResponse.text();

        console.error(
          "Supabase upload failed:",
          errorText
        );

        return res.status(500).json({
          error:
            "Failed to upload image to Supabase."
        });
      }

      const publicUrl =
        `${SUPABASE_URL}/storage/v1/object/public/news-images/${filename}`;

      res.json({
        url: publicUrl
      });

    } catch (e) {
      console.error(
        "Image upload error:",
        e
      );

      res.status(500).json({
        error: "Image upload failed."
      });
    }
  }
);

/* ==========================================
   HOMEPAGE SECTIONS
========================================== */

app.get(
  "/api/sections",
  async (req, res) => {
    try {
      const r = await query(`
        SELECT
          s.*,
          c.name AS category_name,
          c.slug AS category_slug
        FROM homepage_sections s
        LEFT JOIN categories c
          ON c.id=s.category_id
        ORDER BY s.position,s.id
      `);

      res.json(r.rows);
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to load sections"
      });
    }
  }
);

app.post(
  "/api/sections",
  requireAuth,
  async (req, res) => {
    try {
      const {
        title,
        section_type = "category",
        category_id,
        position = 0,
        columns_count = 2,
        enabled = true
      } = req.body;

      const r = await query(
        `
        INSERT INTO homepage_sections
        (
          title,
          section_type,
          category_id,
          position,
          columns_count,
          enabled
        )
        VALUES($1,$2,$3,$4,$5,$6)
        RETURNING *
        `,
        [
          title,
          section_type,
          category_id || null,
          position,
          columns_count,
          !!enabled
        ]
      );

      res.json(r.rows[0]);
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to create section"
      });
    }
  }
);

app.put(
  "/api/sections/:id",
  requireAuth,
  async (req, res) => {
    try {
      const {
        title,
        section_type,
        category_id,
        position,
        columns_count,
        enabled
      } = req.body;

      await query(
        `
        UPDATE homepage_sections
        SET
          title=$1,
          section_type=$2,
          category_id=$3,
          position=$4,
          columns_count=$5,
          enabled=$6
        WHERE id=$7
        `,
        [
          title,
          section_type,
          category_id || null,
          position,
          columns_count,
          !!enabled,
          req.params.id
        ]
      );

      res.json({ ok: true });
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to update section"
      });
    }
  }
);

app.delete(
  "/api/sections/:id",
  requireAuth,
  async (req, res) => {
    try {
      await query(
        `DELETE FROM homepage_sections WHERE id=$1`,
        [req.params.id]
      );

      res.json({ ok: true });
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to delete section"
      });
    }
  }
);

/* ==========================================
   EVENTS
========================================== */

app.get("/api/events", async (req, res) => {
  try {
    const r = await query(`
      SELECT *
      FROM events
      WHERE enabled=TRUE
      ORDER BY position,id
    `);

    res.json(r.rows);
  } catch (e) {
    console.error(e);
    res.status(500).json({
      error: "Failed to load events"
    });
  }
});

app.post(
  "/api/events",
  requireAuth,
  async (req, res) => {
    try {
      const {
        title,
        event_date,
        event_time,
        location,
        description,
        enabled = true,
        position = 0
      } = req.body;

      const r = await query(
        `
        INSERT INTO events
        (
          title,
          event_date,
          event_time,
          location,
          description,
          enabled,
          position
        )
        VALUES($1,$2,$3,$4,$5,$6,$7)
        RETURNING *
        `,
        [
          title,
          event_date || null,
          event_time || "",
          location || "",
          description || "",
          !!enabled,
          position
        ]
      );

      res.json(r.rows[0]);
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to create event"
      });
    }
  }
);

/* ==========================================
   TRENDING
========================================== */

app.get(
  "/api/trending",
  async (req, res) => {
    try {
      const r = await query(`
        SELECT *
        FROM trending_topics
        WHERE enabled=TRUE
        ORDER BY position,id
      `);

      res.json(r.rows);
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to load trending"
      });
    }
  }
);

app.post(
  "/api/trending",
  requireAuth,
  async (req, res) => {
    try {
      const {
        label,
        slug,
        position = 0,
        enabled = true
      } = req.body;

      const r = await query(
        `
        INSERT INTO trending_topics
        (
          label,
          slug,
          position,
          enabled
        )
        VALUES($1,$2,$3,$4)
        RETURNING *
        `,
        [
          label,
          slug || slugify(label),
          position,
          !!enabled
        ]
      );

      res.json(r.rows[0]);
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to create trending topic"
      });
    }
  }
);

/* ==========================================
   NAVIGATION
========================================== */

app.get(
  "/api/navigation",
  async (req, res) => {
    try {
      const r = await query(`
        SELECT *
        FROM navigation
        WHERE enabled=TRUE
        ORDER BY position,id
      `);

      res.json(r.rows);
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to load navigation"
      });
    }
  }
);

app.post(
  "/api/navigation",
  requireAuth,
  async (req, res) => {
    try {
      const {
        label,
        url,
        position = 0,
        enabled = true
      } = req.body;

      const r = await query(
        `
        INSERT INTO navigation
        (
          label,
          url,
          position,
          enabled
        )
        VALUES($1,$2,$3,$4)
        RETURNING *
        `,
        [
          label,
          url,
          position,
          !!enabled
        ]
      );

      res.json(r.rows[0]);
    } catch (e) {
      console.error(e);
      res.status(500).json({
        error: "Failed to create navigation item"
      });
    }
  }
);

/* ==========================================
   ADMIN
========================================== */

app.get(
  "/admin",
  (req, res) =>
    res.sendFile(
      path.join(
        ROOT,
        "public",
        "admin.html"
      )
    )
);

/* ==========================================
   SPA FALLBACK
========================================== */

app.get("/*splat", (req, res) => {
  if (req.path.startsWith("/api/")) {
    return res.status(404).end();
  }

  res.sendFile(
    path.join(
      ROOT,
      "public",
      "index.html"
    )
  );
});

/* ==========================================
   START
========================================== */

setup()
  .then(() => {
    app.listen(PORT, () => {
      console.log(
        `YouthNews running on port ${PORT}`
      );
    });
  })
  .catch(err => {
    console.error(
      "Database startup failed:",
      err
    );
    process.exit(1);
  });
