const express = require("express");
const session = require("express-session");
const pgSession = require("connect-pg-simple")(session);
const { Pool } = require("pg");
const helmet = require("helmet");
const multer = require("multer");
const path = require("path");
const crypto = require("crypto");

const app = express();
const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const isProduction = process.env.NODE_ENV === "production";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.");
  process.exit(1);
}
if (!process.env.DATABASE_URL) {
  console.error("Missing DATABASE_URL.");
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
  max: 10,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000
});

const query = (text, params = []) => pool.query(text, params);
const hash = value => crypto.createHash("sha256").update(String(value)).digest("hex");
const slugify = value => String(value || "").trim().toLowerCase()
  .replace(/[^\u0E00-\u0E7Fa-z0-9]+/g, "-").replace(/^-+|-+$/g, "")
  || crypto.randomBytes(5).toString("hex");
const bool = value => value === true || value === 1 || value === "1" || value === "true";
const int = (value, fallback = 0) => Number.isFinite(Number(value)) ? Math.trunc(Number(value)) : fallback;
const articleRow = row => ({ ...row, featured: !!row.featured });

app.set("trust proxy", 1);
app.disable("x-powered-by");
app.use(helmet({ contentSecurityPolicy: false, crossOriginEmbedderPolicy: false }));
app.use(express.json({ limit: "2mb" }));
app.use(express.urlencoded({ extended: true }));

app.use(session({
  store: new pgSession({ pool, tableName: "user_sessions", createTableIfMissing: true }),
  secret: process.env.SESSION_SECRET || "CHANGE_THIS_SESSION_SECRET",
  resave: false,
  saveUninitialized: false,
  rolling: true,
  cookie: { httpOnly: true, sameSite: "lax", secure: isProduction, maxAge: 8 * 60 * 60 * 1000 }
}));

function requireAuth(req, res, next) {
  if (req.session?.user) return next();
  return res.status(401).json({ error: "Please login first." });
}

async function setup() {
  await query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS categories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT UNIQUE NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS articles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      excerpt TEXT DEFAULT '',
      content TEXT DEFAULT '',
      image TEXT DEFAULT '',
      category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
      author TEXT DEFAULT 'YouthNews',
      status TEXT DEFAULT 'published',
      featured BOOLEAN DEFAULT FALSE,
      views BIGINT DEFAULT 0,
      published_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS homepage_sections (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      section_type TEXT DEFAULT 'category',
      category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
      position INTEGER DEFAULT 0,
      columns_count INTEGER DEFAULT 2,
      article_limit INTEGER DEFAULT 2,
      enabled BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      event_date DATE,
      event_time TEXT DEFAULT '',
      location TEXT DEFAULT '',
      description TEXT DEFAULT '',
      enabled BOOLEAN DEFAULT TRUE,
      position INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS trending_topics (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label TEXT NOT NULL,
      slug TEXT NOT NULL,
      position INTEGER DEFAULT 0,
      enabled BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS navigation (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label TEXT NOT NULL,
      url TEXT NOT NULL,
      position INTEGER DEFAULT 0,
      enabled BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
    ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS article_limit INTEGER DEFAULT 2;
    ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS columns_count INTEGER DEFAULT 2;
  `);

  await query(`ALTER TABLE homepage_sections ALTER COLUMN article_limit SET DEFAULT 2`);
  await query(`UPDATE homepage_sections SET article_limit=2 WHERE article_limit IS NULL`);
  await query(`UPDATE homepage_sections SET columns_count=2 WHERE columns_count IS NULL`);

  const categories = [
    ["RMUTK News", "rmutk-news"], ["General", "general"], ["Training News", "training-news"],
    ["Career", "career"], ["Student Voice", "student-voice"]
  ];
  for (const [name, slug] of categories) {
    await query(`INSERT INTO categories(name,slug) VALUES($1,$2) ON CONFLICT(slug) DO NOTHING`, [name, slug]);
  }

  const settings = [
    ["site_name", "YOUTH NEWS"], ["tagline", "Stories for the next generation."],
    ["breaking", "Latest updates from the campus community."], ["search_placeholder", "Search news, people, or topics..."],
    ["hero_button", "Read More"], ["footer_text", "Â© Youth News Â· Stories for the next generation."],
    ["facebook", "#"], ["instagram", "#"], ["contact", "news@youthnews.local"]
  ];
  for (const [key, value] of settings) {
    await query(`INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO NOTHING`, [key, value]);
  }

  const nav = [
    ["Home", "/", 1], ["RMUTK News", "/?category=rmutk-news", 2], ["General", "/?category=general", 3],
    ["Training News", "/?category=training-news", 4], ["Career", "/?category=career", 5], ["Student Voice", "/?category=student-voice", 6]
  ];
  for (const [label, url, position] of nav) {
    const existingNav = await query(`SELECT id FROM navigation WHERE label=$1 LIMIT 1`, [label]);
    if (!existingNav.rowCount) {
      await query(`INSERT INTO navigation(label,url,position,enabled) VALUES($1,$2,$3,TRUE)`, [label, url, position]);
    }
  }

  const username = process.env.ADMIN_USER || "admin";
  const password = process.env.ADMIN_PASSWORD || "change-me-now";
  const existing = await query(`SELECT id FROM users WHERE username=$1 LIMIT 1`, [username]);
  if (!existing.rowCount) await query(`INSERT INTO users(username,password_hash) VALUES($1,$2)`, [username, hash(password)]);
}

function publicArticleWhere(queryParams) {
  const conditions = ["a.status='published'"];
  const params = [];
  if (queryParams.category) { params.push(queryParams.category); conditions.push(`c.slug=$${params.length}`); }
  if (queryParams.featured === "1") conditions.push("a.featured=TRUE");
  if (queryParams.search) { params.push(`%${queryParams.search}%`); const p = `$${params.length}`; conditions.push(`(a.title ILIKE ${p} OR a.excerpt ILIKE ${p} OR a.content ILIKE ${p})`); }
  return { conditions, params };
}

app.get("/api/settings", async (_req, res) => {
  try { const r = await query("SELECT key,value FROM settings"); res.json(Object.fromEntries(r.rows.map(x => [x.key, x.value]))); }
  catch (e) { console.error(e); res.status(500).json({ error: "Failed to load settings" }); }
});
app.put("/api/settings", requireAuth, async (req, res) => {
  try {
    for (const [key, value] of Object.entries(req.body || {})) await query(`INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value`, [key, String(value ?? "")]);
    res.json({ ok: true });
  } catch (e) { console.error(e); res.status(500).json({ error: "Failed to save settings" }); }
});

app.get("/api/categories", async (_req, res) => {
  try { const r = await query("SELECT * FROM categories ORDER BY id"); res.json(r.rows); }
  catch (e) { console.error(e); res.status(500).json({ error: "Failed to load categories" }); }
});
app.post("/api/categories", requireAuth, async (req, res) => {
  try { const name = String(req.body.name || "").trim(); if (!name) return res.status(400).json({ error: "Category name is required." }); const slug = String(req.body.slug || slugify(name)).trim(); const r = await query(`INSERT INTO categories(name,slug) VALUES($1,$2) RETURNING *`, [name, slug]); res.json(r.rows[0]); }
  catch (e) { console.error(e); res.status(400).json({ error: "Category already exists or is invalid." }); }
});
app.put("/api/categories/:id", requireAuth, async (req, res) => {
  try { const name = String(req.body.name || "").trim(); if (!name) return res.status(400).json({ error: "Category name is required." }); const slug = String(req.body.slug || slugify(name)).trim(); const r = await query(`UPDATE categories SET name=$1,slug=$2 WHERE id=$3 RETURNING *`, [name, slug, req.params.id]); if (!r.rowCount) return res.status(404).json({ error: "Category not found" }); res.json(r.rows[0]); }
  catch (e) { console.error(e); res.status(400).json({ error: "Failed to update category" }); }
});
app.delete("/api/categories/:id", requireAuth, async (req, res) => {
  try { await query("DELETE FROM categories WHERE id=$1", [req.params.id]); res.json({ ok: true }); }
  catch (e) { console.error(e); res.status(500).json({ error: "Failed to delete category" }); }
});

app.get("/api/articles", async (req, res) => {
  try {
    const status = req.query.status;
    if (status === "all" || status === "draft") {
      if (!req.session?.user) return res.status(401).json({ error: "Please login first." });
    }
    const conditions = [];
    const params = [];
    if (status === "all") { }
    else if (status === "draft") { params.push("draft"); conditions.push(`a.status=$${params.length}`); }
    else { conditions.push("a.status='published'"); }
    if (req.query.category) { params.push(req.query.category); conditions.push(`c.slug=$${params.length}`); }
    if (req.query.featured === "1") conditions.push("a.featured=TRUE");
    if (req.query.search) { params.push(`%${req.query.search}%`); const p = `$${params.length}`; conditions.push(`(a.title ILIKE ${p} OR a.excerpt ILIKE ${p} OR a.content ILIKE ${p})`); }
    const limit = Math.min(Math.max(int(req.query.limit, 30), 1), 100);
    const page = Math.max(int(req.query.page, 1), 1);
    params.push(limit); const lp = `$${params.length};`; params[params.length-1] = limit;
    params.push((page - 1) * limit); const op = `$${params.length}`;
    const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";
    const order = status === "all" ? "a.updated_at DESC,a.published_at DESC" : "a.featured DESC,a.published_at DESC";
    const r = await query(`SELECT a.*,c.name AS category_name,c.slug AS category_slug FROM articles a LEFT JOIN categories c ON c.id=a.category_id ${where} ORDER BY ${order} LIMIT ${lp.slice(0,-1)} OFFSET ${op}`, params);
    res.json(r.rows.map(articleRow));
  } catch (e) { console.error(e); res.status(500).json({ error: "Failed to load articles" }); }
});

app.get("/api/articles/:slug", async (req, res) => {
  try {
    const r = await query(`SELECT a.*,c.name AS category_name,c.slug AS category_slug FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.slug=$1 AND a.status='published'`, [req.params.slug]);
    if (!r.rowCount) return res.status(404).json({ error: "Article not found" });
    const a = r.rows[0]; await query("UPDATE articles SET views=views+1 WHERE id=$1", [a.id]); a.views = Number(a.views || 0) + 1; res.json(articleRow(a));
  } catch (e) { console.error(e); res.status(500).json({ error: "Failed to load article" }); }
});

app.post("/api/articles", requireAuth, async (req, res) => {
  try {
    const title = String(req.body.title || "").trim(); if (!title) return res.status(400).json({ error: "Title is required." });
    const slug = slugify(title) + "-" + Date.now().toString().slice(-6);
    const status = req.body.status === "draft" ? "draft" : "published";
    const r = await query(`INSERT INTO articles(title,slug,excerpt,content,image,category_id,author,status,featured,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,CASE WHEN $8='published' THEN NOW() ELSE NULL END) RETURNING *`, [title, req.body.slug || slug, req.body.excerpt || "", req.body.content || "", req.body.image || "", req.body.category_id || null, req.body.author || "YouthNews", status, bool(req.body.featured)]);
    res.json(articleRow(r.rows[0]));
  } catch (e) { console.error(e); res.status(500).json({ error: "Failed to create article" }); }
});
app.put("/api/articles/:id", requireAuth, async (req, res) => {
  try {
    const status = req.body.status === "draft" ? "draft" : "published";
    const r = await query(`UPDATE articles SET title=$1,excerpt=$2,content=$3,image=$4,category_id=$5,author=$6,status=$7,featured=$8,published_at=CASE WHEN $7='published' AND published_at IS NULL THEN NOW() ELSE published_at END,updated_at=NOW() WHERE id=$9 RETURNING *`, [req.body.title, req.body.excerpt || "", req.body.content || "", req.body.image || "", req.body.category_id || null, req.body.author || "YouthNews", status, bool(req.body.featured), req.params.id]);
    if (!r.rowCount) return res.status(404).json({ error: "Article not found" }); res.json({ ok: true, article: articleRow(r.rows[0]) });
  } catch (e) { console.error(e); res.status(500).json({ error: "Failed to update article" }); }
});
app.delete("/api/articles/:id", requireAuth, async (req, res) => {
  try { await query("DELETE FROM articles WHERE id=$1", [req.params.id]); res.json({ ok: true }); }
  catch (e) { console.error(e); res.status(500).json({ error: "Failed to delete article" }); }
});

app.post("/api/login", async (req, res) => {
  try {
    const username = String(req.body.username || "").trim(); const password = String(req.body.password || "");
    if (!username || !password) return res.status(400).json({ error: "Username and password are required." });
    const r = await query("SELECT id,username,password_hash FROM users WHERE username=$1 LIMIT 1", [username]);
    if (!r.rowCount || hash(password) !== r.rows[0].password_hash) return res.status(401).json({ error: "Invalid username or password." });
    req.session.regenerate(err => {
      if (err) { console.error(err); return res.status(500).json({ error: "Could not create login session." }); }
      req.session.user = { id: r.rows[0].id, username: r.rows[0].username };
      req.session.save(saveErr => { if (saveErr) { console.error(saveErr); return res.status(500).json({ error: "Could not save login session." }); } res.json({ ok: true, username: r.rows[0].username }); });
    });
  } catch (e) { console.error(e); res.status(500).json({ error: "Login failed" }); }
});
app.post("/api/logout", (req, res) => {
  if (!req.session) return res.json({ ok: true });
  req.session.destroy(err => { if (err) return res.status(500).json({ error: "Logout failed" }); res.clearCookie("connect.sid", { httpOnly: true, sameSite: "lax", secure: isProduction }); res.json({ ok: true }); });
});
app.get("/api/me", (req, res) => res.json(req.session?.user || null));

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, /^image\/(jpeg|png|webp|gif)$/.test(file.mimetype)) });
app.post("/api/upload", requireAuth, upload.single("image"), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: "Please select a JPG, PNG, WEBP, or GIF image." });
    const ext = path.extname(req.file.originalname).toLowerCase() || ".jpg";
    const storagePath = `articles/${Date.now()}-${crypto.randomBytes(6).toString("hex")}${ext}`;
    const uploadUrl = `${SUPABASE_URL}/storage/v1/object/news-images/${storagePath}`;
    const response = await fetch(uploadUrl, { method: "POST", headers: { Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`, apikey: SUPABASE_SERVICE_ROLE_KEY, "Content-Type": req.file.mimetype, "x-upsert": "false" }, body: req.file.buffer });
    if (!response.ok) { console.error("Supabase upload:", await response.text()); return res.status(500).json({ error: "Failed to upload image to Supabase." }); }
    res.json({ url: `${SUPABASE_URL}/storage/v1/object/public/news-images/${storagePath}` });
  } catch (e) { console.error(e); res.status(500).json({ error: "Image upload failed." }); }
});

app.get("/api/sections", async (req, res) => {
  try {
    const admin = req.query.admin === "1" && req.session?.user;
    const r = await query(`SELECT s.*,c.name AS category_name,c.slug AS category_slug FROM homepage_sections s LEFT JOIN categories c ON c.id=s.category_id ${admin ? "" : "WHERE s.enabled=TRUE"} ORDER BY s.position,s.id`);
    res.json(r.rows);
  } catch (e) { console.error(e); res.status(500).json({ error: "Failed to load sections" }); }
});
app.post("/api/sections", requireAuth, async (req, res) => {
  try { const title = String(req.body.title || "").trim(); if (!title) return res.status(400).json({ error: "Section title is required." }); const r = await query(`INSERT INTO homepage_sections(title,section_type,category_id,position,columns_count,article_limit,enabled) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`, [title, req.body.section_type || "category", req.body.category_id || null, int(req.body.position), Math.min(Math.max(int(req.body.columns_count,2),1),4), Math.min(Math.max(int(req.body.article_limit,2),1),12), bool(req.body.enabled)]); res.json(r.rows[0]); }
  catch (e) { console.error(e); res.status(500).json({ error: "Failed to create section" }); }
});
app.put("/api/sections/:id", requireAuth, async (req, res) => {
  try { const r = await query(`UPDATE homepage_sections SET title=$1,section_type=$2,category_id=$3,position=$4,columns_count=$5,article_limit=$6,enabled=$7 WHERE id=$8 RETURNING *`, [req.body.title, req.body.section_type || "category", req.body.category_id || null, int(req.body.position), Math.min(Math.max(int(req.body.columns_count,2),1),4), Math.min(Math.max(int(req.body.article_limit,2),1),12), bool(req.body.enabled), req.params.id]); if (!r.rowCount) return res.status(404).json({ error: "Section not found" }); res.json({ ok: true, section: r.rows[0] }); }
  catch (e) { console.error(e); res.status(500).json({ error: "Failed to update section" }); }
});
app.delete("/api/sections/:id", requireAuth, async (req, res) => { try { await query("DELETE FROM homepage_sections WHERE id=$1", [req.params.id]); res.json({ ok: true }); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to delete section" }); } });

app.get("/api/events", async (req, res) => {
  try { const admin = req.query.admin === "1" && req.session?.user; const r = await query(`SELECT * FROM events ${admin ? "" : "WHERE enabled=TRUE"} ORDER BY position,id`); res.json(r.rows); }
  catch (e) { console.error(e); res.status(500).json({ error: "Failed to load events" }); }
});
app.post("/api/events", requireAuth, async (req, res) => { try { if (!req.body.title) return res.status(400).json({ error: "Event title is required." }); const r = await query(`INSERT INTO events(title,event_date,event_time,location,description,enabled,position) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`, [req.body.title, req.body.event_date || null, req.body.event_time || "", req.body.location || "", req.body.description || "", bool(req.body.enabled), int(req.body.position)]); res.json(r.rows[0]); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to create event" }); } });
app.put("/api/events/:id", requireAuth, async (req, res) => { try { const r = await query(`UPDATE events SET title=$1,event_date=$2,event_time=$3,location=$4,description=$5,enabled=$6,position=$7 WHERE id=$8 RETURNING *`, [req.body.title, req.body.event_date || null, req.body.event_time || "", req.body.location || "", req.body.description || "", bool(req.body.enabled), int(req.body.position), req.params.id]); if (!r.rowCount) return res.status(404).json({ error: "Event not found" }); res.json({ ok: true, event: r.rows[0] }); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to update event" }); } });
app.delete("/api/events/:id", requireAuth, async (req, res) => { try { await query("DELETE FROM events WHERE id=$1", [req.params.id]); res.json({ ok: true }); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to delete event" }); } });

app.get("/api/trending", async (req, res) => { try { const admin = req.query.admin === "1" && req.session?.user; const r = await query(`SELECT * FROM trending_topics ${admin ? "" : "WHERE enabled=TRUE"} ORDER BY position,id`); res.json(r.rows); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to load trending" }); } });
app.post("/api/trending", requireAuth, async (req, res) => { try { if (!req.body.label) return res.status(400).json({ error: "Trending label is required." }); const r = await query(`INSERT INTO trending_topics(label,slug,position,enabled) VALUES($1,$2,$3,$4) RETURNING *`, [req.body.label, req.body.slug || slugify(req.body.label), int(req.body.position), bool(req.body.enabled)]); res.json(r.rows[0]); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to create trending topic" }); } });
app.put("/api/trending/:id", requireAuth, async (req, res) => { try { const r = await query(`UPDATE trending_topics SET label=$1,slug=$2,position=$3,enabled=$4 WHERE id=$5 RETURNING *`, [req.body.label, req.body.slug || slugify(req.body.label), int(req.body.position), bool(req.body.enabled), req.params.id]); if (!r.rowCount) return res.status(404).json({ error: "Trending topic not found" }); res.json({ ok: true, trending: r.rows[0] }); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to update trending topic" }); } });
app.delete("/api/trending/:id", requireAuth, async (req, res) => { try { await query("DELETE FROM trending_topics WHERE id=$1", [req.params.id]); res.json({ ok: true }); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to delete trending topic" }); } });

app.get("/api/navigation", async (req, res) => { try { const admin = req.query.admin === "1" && req.session?.user; const r = await query(`SELECT * FROM navigation ${admin ? "" : "WHERE enabled=TRUE"} ORDER BY position,id`); res.json(r.rows); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to load navigation" }); } });
app.post("/api/navigation", requireAuth, async (req, res) => { try { if (!req.body.label || !req.body.url) return res.status(400).json({ error: "Label and URL are required." }); const r = await query(`INSERT INTO navigation(label,url,position,enabled) VALUES($1,$2,$3,$4) RETURNING *`, [req.body.label, req.body.url, int(req.body.position), bool(req.body.enabled)]); res.json(r.rows[0]); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to create navigation item" }); } });
app.put("/api/navigation/:id", requireAuth, async (req, res) => { try { const r = await query(`UPDATE navigation SET label=$1,url=$2,position=$3,enabled=$4 WHERE id=$5 RETURNING *`, [req.body.label, req.body.url, int(req.body.position), bool(req.body.enabled), req.params.id]); if (!r.rowCount) return res.status(404).json({ error: "Navigation item not found" }); res.json({ ok: true, navigation: r.rows[0] }); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to update navigation item" }); } });
app.delete("/api/navigation/:id", requireAuth, async (req, res) => { try { await query("DELETE FROM navigation WHERE id=$1", [req.params.id]); res.json({ ok: true }); } catch (e) { console.error(e); res.status(500).json({ error: "Failed to delete navigation item" }); } });

app.get("/admin", (_req, res) => res.sendFile(path.join(ROOT, "public", "admin.html")));
app.use(express.static(path.join(ROOT, "public"), { extensions: ["html"] }));
app.get("/*splat", (req, res) => { if (req.path.startsWith("/api/")) return res.status(404).json({ error: "Not found" }); res.sendFile(path.join(ROOT, "public", "index.html")); });

process.on("SIGTERM", async () => { await pool.end(); process.exit(0); });
process.on("SIGINT", async () => { await pool.end(); process.exit(0); });

setup().then(() => app.listen(PORT, () => console.log(`YouthNews running on port ${PORT}`))).catch(err => { console.error("Database startup failed:", err); process.exit(1); });
